language: python
dist: xenial

matrix:
  include:
  - python: '3.5'
    env: NOXSESSION="tests-3.5"
  - python: '3.6'
    env: NOXSESSION="tests-3.6"
  - python: '3.7'
    env: NOXSESSION="tests-3.7"
    sudo: required  # required for Python 3.7 (github.com/travis-ci/travis-ci#9069)
  - python: '3.8'
    env: NOXSESSION="tests-3.8"
  - python: '3.6'
    env: NOXSESSION="docs"

install:
- ./.travis/install.sh

script:
- python3 -m nox --session "$NOXSESSION"
- python3 -m nox -e distribution

deploy:
  on:
    tags: true
    python: '3.6'  # only run this deploy once with python 3.6
  provider: pypi
  distributions: 'sdist bdist_wheel'
  user: __token__  # api token encrypted within travis
  skip_existing: true

notifications:
  email: false
